services:
  - type: web
    name: brain-tumor-detector
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn minorproject.wsgi --log-file -
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "False"
      - key: KAGGLE_USERNAME
        value: your-kaggle-username
      - key: KAGGLE_KEY
        value: your-kaggle-key
